#!/usr/bin/env python3
"""Regenerates docs/THIRD_PARTY_NOTICES.md from what the app actually ships:
npm production dependencies (bundled into the webview) and every Rust crate
linked into the binary. Run before a release: scripts/licenses.py"""

import json
import pathlib
import subprocess

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "docs" / "THIRD_PARTY_NOTICES.md"
# Fonts ship inside the bundle, and the OFL asks for its text to go with them.
FONTS = ["@fontsource/jetbrains-mono", "@fontsource/nanum-gothic-coding"]


def npm_packages():
    tree = json.loads(
        subprocess.run(
            ["npm", "ls", "--omit=dev", "--all", "--json"],
            cwd=ROOT, capture_output=True, text=True, check=False,
        ).stdout
    )
    found = {}

    def walk(deps):
        for name, info in (deps or {}).items():
            version = info.get("version")
            if not version or (name, version) in found:
                continue
            manifest = ROOT / "node_modules" / name / "package.json"
            license_ = "?"
            if manifest.exists():
                data = json.loads(manifest.read_text())
                license_ = data.get("license") or "?"
            found[(name, version)] = license_
            walk(info.get("dependencies"))

    walk(tree.get("dependencies"))
    return sorted(found.items())


def crates():
    meta = json.loads(
        subprocess.run(
            ["cargo", "metadata", "--format-version", "1", "--filter-platform", "aarch64-apple-darwin"],
            cwd=ROOT / "src-tauri", capture_output=True, text=True, check=True,
        ).stdout
    )
    ids = {n["id"] for n in meta["resolve"]["nodes"]}
    rows = []
    for p in meta["packages"]:
        if p["id"] in ids and p["name"] != "burrow":
            rows.append(((p["name"], p["version"]), p.get("license") or "?"))
    return sorted(rows)


def main():
    lines = [
        "# Third-party notices",
        "",
        "Burrow includes the software below. Generated by `scripts/licenses.py`; do not edit by hand.",
        "",
        "## Frontend (npm, bundled)",
        "",
        "| Package | Version | License |",
        "|---|---|---|",
    ]
    lines += [f"| {n} | {v} | {l} |" for (n, v), l in npm_packages()]
    lines += ["", "## Native (Rust crates, linked)", "", "| Crate | Version | License |", "|---|---|---|"]
    lines += [f"| {n} | {v} | {l} |" for (n, v), l in crates()]
    for font in FONTS:
        lic = next((p for p in (ROOT / "node_modules" / font).glob("LICENSE*")), None)
        lines += ["", f"## {font} — SIL Open Font License 1.1", ""]
        lines += ["```", lic.read_text().strip() if lic else "(license file missing)", "```"]
    OUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
