//! Guardrails: guardrails.json turned into the rule arrays the zsh hooks read,
//! and into a Claude Code `PreToolUse` hook — agents run commands in their own
//! subprocesses, so the shell's accept-line never sees them.
//!
//! Patterns are zsh `=~` expressions (POSIX ERE). Nothing here reimplements
//! that dialect: testing a pattern runs zsh itself.

use std::path::{Path, PathBuf};
use std::process::Command;
use std::sync::Arc;

use serde::{Deserialize, Serialize};
use serde_json::{json, Value};

use crate::remote;
use crate::store::{GuardrailsFile, Severity, Store};

const RULES_FILE: &str = "guardrails.zsh";
const CLAUDE_HOOK_FILE: &str = "guardrail-hook.zsh";

fn quote(s: &str) -> String {
    format!("'{}'", s.replace('\'', "'\\''"))
}

fn fnv(text: &str) -> String {
    let mut hash: u64 = 0xcbf2_9ce4_8422_2325;
    for byte in text.bytes() {
        hash ^= u64::from(byte);
        hash = hash.wrapping_mul(0x0000_0100_0000_01b3);
    }
    format!("{hash:016x}")
}

/// Three parallel zsh arrays of the enabled rules.
fn rule_arrays(file: &GuardrailsFile, prefix: &str) -> String {
    let rules: Vec<_> = file
        .rules
        .iter()
        .filter(|r| r.enabled && !r.pattern.is_empty())
        .collect();
    let list = |f: &dyn Fn(&crate::store::GuardrailRule) -> String| {
        rules.iter().map(|r| f(r)).collect::<Vec<_>>().join(" ")
    };
    let severity = |r: &crate::store::GuardrailRule| {
        match r.severity {
            Severity::Block => "block",
            Severity::Warn => "warn",
        }
        .to_string()
    };
    format!(
        "{prefix}patterns=({})\n{prefix}severity=({})\n{prefix}labels=({})\n",
        list(&|r| quote(&r.pattern)),
        list(&severity),
        list(&|r| quote(&r.label)),
    )
}

/// The file burrow-hooks.zsh sources. Its first line is a stamp so shells
/// re-read it only after it changed.
pub fn zsh_rules(file: &GuardrailsFile) -> String {
    let body = rule_arrays(file, "__burrow_guard_");
    format!(
        "# burrow-guardrails {}\n# Generated by Burrow from guardrails.json; edits here are overwritten.\n{body}",
        fnv(&body)
    )
}

/// A PreToolUse hook for Claude Code: Bash tool calls matching a `block` rule
/// are denied with the rule's label as the reason, so the agent tells the user
/// instead of running it. `warn` rules don't stop agents.
pub fn claude_hook(file: &GuardrailsFile) -> String {
    format!(
        r#"#!/usr/bin/env zsh
# Burrow guardrails for Claude Code (PreToolUse hook). Generated by Burrow from
# guardrails.json; edits here are overwritten.
{rules}
input=$(cat)
[[ $input =~ '"tool_name"[[:space:]]*:[[:space:]]*"Bash"' ]] || exit 0
[[ $input =~ '"command"[[:space:]]*:[[:space:]]*"(([^"\\]|\\.)*)"' ]] || exit 0
cmd=$match[1]
# The JSON escapes that change what a command looks like.
cmd=${{cmd//\\\\/$'\x01'}}
cmd=${{cmd//\\\"/\"}}
cmd=${{cmd//\\n/$'\n'}}
cmd=${{cmd//\\t/$'\t'}}
cmd=${{cmd//$'\x01'/\\}}
for i in {{1..${{#patterns}}}}; do
  [[ ${{severity[i]}} == block ]] || continue
  [[ $cmd =~ ${{patterns[i]}} ]] 2>/dev/null || continue
  reason="Burrow 가드레일: ${{labels[i]}} — 위험 명령이라 막았습니다. 필요하면 사용자가 터미널에서 직접 실행하게 안내하세요."
  reason=${{reason//\\/\\\\}}
  reason=${{reason//\"/\\\"}}
  print -r -- '{{"hookSpecificOutput":{{"hookEventName":"PreToolUse","permissionDecision":"deny","permissionDecisionReason":"'"$reason"'"}}}}'
  exit 0
done
exit 0
"#,
        rules = rule_arrays(file, "")
    )
}

fn write_private(path: &Path, contents: &str) -> std::io::Result<()> {
    use std::os::unix::fs::PermissionsExt;
    if let Some(dir) = path.parent() {
        std::fs::create_dir_all(dir)?;
    }
    let tmp = path.with_extension("tmp");
    std::fs::write(&tmp, contents)?;
    std::fs::set_permissions(&tmp, std::fs::Permissions::from_mode(0o600))?;
    std::fs::rename(tmp, path)
}

fn local_hook_path(store: &Store) -> PathBuf {
    store.root().join("claude").join(CLAUDE_HOOK_FILE)
}

/// Rewrites the local rules file, and the local Claude hook if it's installed.
pub fn write_local(store: &Store) -> std::io::Result<()> {
    let file = store.load::<GuardrailsFile>();
    write_private(
        &store.root().join("shell/zsh").join(RULES_FILE),
        &zsh_rules(&file),
    )?;
    let hook = local_hook_path(store);
    if hook.exists() {
        write_private(&hook, &claude_hook(&file))?;
    }
    Ok(())
}

/// Which rules a command line hits, by asking zsh — the same engine the hook
/// uses. Also reports patterns zsh can't compile.
#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
pub struct TestResult {
    matched: Vec<String>,
    invalid: Vec<String>,
}

#[tauri::command(async)]
pub fn guardrail_test(
    command: String,
    patterns: Vec<(String, String)>,
) -> Result<TestResult, String> {
    // Everything goes in as arguments: nothing from the webview is evaluated.
    let script = r#"
cmd=$1; shift
while (( $# >= 2 )); do
  id=$1 pat=$2; shift 2
  # A pattern zsh can't compile fails like a non-match, but says so on stderr.
  if [[ -n $( { [[ x =~ $pat ]] } 2>&1 ) ]]; then print -r -- "invalid:$id"; continue; fi
  [[ $cmd =~ $pat ]] && print -r -- "match:$id"
done
"#;
    let mut args = vec![command];
    for (id, pattern) in patterns {
        args.push(id);
        args.push(pattern);
    }
    let out = Command::new("zsh")
        .args(["-f", "-c", script, "zsh"])
        .args(&args)
        .output()
        .map_err(|e| e.to_string())?;
    let text = String::from_utf8_lossy(&out.stdout);
    let pick = |prefix: &str| {
        text.lines()
            .filter_map(|l| l.strip_prefix(prefix).map(str::to_string))
            .collect()
    };
    Ok(TestResult {
        matched: pick("match:"),
        invalid: pick("invalid:"),
    })
}

/// Pushes the current rules to a host whose hooks are installed; also refreshes
/// Burrow's Claude hook there if the user installed it. Writes nothing else.
#[tauri::command(async)]
pub fn remote_sync_guardrails(
    store: tauri::State<'_, Arc<Store>>,
    profile_id: String,
) -> Result<(), String> {
    let profile = remote::load_profile(&store, &profile_id)?;
    let file = store.load::<GuardrailsFile>();
    let script = format!(
        "set -e\nd=\"$HOME/.burrow/shell/zsh\"\n[ -d \"$d\" ] || exit 0\n\
         cat > \"$d/{RULES_FILE}.tmp\" <<'BURROW_EOF'\n{}BURROW_EOF\nmv \"$d/{RULES_FILE}.tmp\" \"$d/{RULES_FILE}\"\n\
         h=\"$HOME/.burrow/claude/{CLAUDE_HOOK_FILE}\"\nif [ -f \"$h\" ]; then\n\
         cat > \"$h.tmp\" <<'BURROW_EOF'\n{}BURROW_EOF\nmv \"$h.tmp\" \"$h\"\nfi\n",
        zsh_rules(&file),
        claude_hook(&file)
    );
    remote::side_command(&store, &profile, "sh -s", Some(script.as_bytes())).map(|_| ())
}

// ---------- installing the Claude Code hook ----------

// rename_all only renames the variant tags; the fields need rename_all_fields,
// or `profileId` from the webview is silently dropped (and a remote install
// would land in this Mac's settings instead).
#[derive(Debug, PartialEq, Deserialize)]
#[serde(
    rename_all = "camelCase",
    rename_all_fields = "camelCase",
    tag = "scope",
    deny_unknown_fields
)]
pub enum ClaudeTarget {
    /// ~/.claude/settings.json
    User { profile_id: Option<String> },
    /// <dir>/.claude/settings.json
    Project {
        profile_id: Option<String>,
        dir: String,
    },
}

/// Adds Burrow's hook to a Claude Code settings object without touching
/// anything else in it. Returns false if it was already there.
fn merge_settings(settings: &mut Value, hook_command: &str) -> Result<bool, String> {
    let root = settings
        .as_object_mut()
        .ok_or("settings.json의 최상위가 객체가 아닙니다")?;
    let hooks = root.entry("hooks").or_insert_with(|| json!({}));
    let hooks = hooks
        .as_object_mut()
        .ok_or("settings.json의 hooks가 객체가 아닙니다")?;
    let pre = hooks.entry("PreToolUse").or_insert_with(|| json!([]));
    let pre = pre
        .as_array_mut()
        .ok_or("hooks.PreToolUse가 배열이 아닙니다")?;
    let present = pre.iter().any(|entry| {
        entry["hooks"].as_array().is_some_and(|hs| {
            hs.iter()
                .any(|h| h["command"].as_str() == Some(hook_command))
        })
    });
    if present {
        return Ok(false);
    }
    pre.push(json!({
        "matcher": "Bash",
        "hooks": [{ "type": "command", "command": hook_command }]
    }));
    Ok(true)
}

fn parse_settings(text: Option<&str>) -> Result<Value, String> {
    match text.map(str::trim) {
        None | Some("") => Ok(json!({})),
        // An unreadable file is left alone rather than "fixed".
        Some(t) => serde_json::from_str(t)
            .map_err(|e| format!("settings.json을 읽을 수 없어 건드리지 않았습니다 ({e})")),
    }
}

fn valid_dir(dir: &str) -> Result<(), String> {
    if dir.starts_with('/') && !dir.contains(['\n', '\0', '\'']) {
        Ok(())
    } else {
        Err(format!("사용할 수 없는 폴더 경로: {dir}"))
    }
}

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
pub struct InstallResult {
    /// The settings file that now references the hook.
    settings: String,
    /// False when the hook was already registered (only the script was refreshed).
    added: bool,
}

#[tauri::command(async)]
pub fn claude_hook_install(
    store: tauri::State<'_, Arc<Store>>,
    target: ClaudeTarget,
) -> Result<InstallResult, String> {
    let file = store.load::<GuardrailsFile>();
    let hook = claude_hook(&file);
    let (profile_id, project_dir) = match &target {
        ClaudeTarget::User { profile_id } => (profile_id.clone(), None),
        ClaudeTarget::Project { profile_id, dir } => {
            valid_dir(dir)?;
            (profile_id.clone(), Some(dir.clone()))
        }
    };
    match profile_id {
        None => {
            let home = PathBuf::from(std::env::var_os("HOME").ok_or("HOME이 없습니다")?);
            let settings_path = match &project_dir {
                Some(dir) => Path::new(dir).join(".claude/settings.json"),
                None => home.join(".claude/settings.json"),
            };
            let hook_path = local_hook_path(&store);
            write_private(&hook_path, &hook).map_err(|e| e.to_string())?;
            let existing = std::fs::read_to_string(&settings_path).ok();
            let mut settings = parse_settings(existing.as_deref())?;
            let command = format!("zsh {}", quote(&hook_path.display().to_string()));
            let added = merge_settings(&mut settings, &command)?;
            if added {
                if let Some(old) = &existing {
                    let _ = std::fs::write(settings_path.with_extension("json.burrow-bak"), old);
                }
                let text =
                    serde_json::to_string_pretty(&settings).map_err(|e| e.to_string())? + "\n";
                if let Some(dir) = settings_path.parent() {
                    std::fs::create_dir_all(dir).map_err(|e| e.to_string())?;
                }
                let tmp = settings_path.with_extension("json.tmp");
                std::fs::write(&tmp, text).map_err(|e| e.to_string())?;
                std::fs::rename(&tmp, &settings_path).map_err(|e| e.to_string())?;
            }
            Ok(InstallResult {
                settings: settings_path.display().to_string(),
                added,
            })
        }
        Some(id) => {
            let profile = remote::load_profile(&store, &id)?;
            let settings_dir = match &project_dir {
                Some(dir) => format!("{}/.claude", quote(dir)),
                None => "\"$HOME/.claude\"".into(),
            };
            // Round trip 1: write the hook script, report $HOME and the settings.
            let read = format!(
                "set -e\nh=\"$HOME/.burrow/claude\"\nmkdir -p \"$h\"\nchmod 700 \"$HOME/.burrow\"\n\
                 cat > \"$h/{CLAUDE_HOOK_FILE}\" <<'BURROW_EOF'\n{hook}BURROW_EOF\n\
                 chmod 600 \"$h/{CLAUDE_HOOK_FILE}\"\n\
                 printf 'burrow:home:%s\\n' \"$HOME\"\n\
                 if [ -f {settings_dir}/settings.json ]; then echo burrow:settings; cat {settings_dir}/settings.json; fi\n"
            );
            let out = remote::side_command(&store, &profile, "sh -s", Some(read.as_bytes()))?;
            let home = out
                .lines()
                .find_map(|l| l.strip_prefix("burrow:home:"))
                .ok_or("원격 HOME을 알 수 없습니다")?
                .to_string();
            let existing = out
                .split_once("burrow:settings\n")
                .map(|(_, s)| s.to_string());
            let mut settings = parse_settings(existing.as_deref())?;
            let command = format!(
                "zsh {}",
                quote(&format!("{home}/.burrow/claude/{CLAUDE_HOOK_FILE}"))
            );
            let added = merge_settings(&mut settings, &command)?;
            let shown = match &project_dir {
                Some(dir) => format!("{dir}/.claude/settings.json"),
                None => format!("{home}/.claude/settings.json"),
            };
            if added {
                let text = serde_json::to_string_pretty(&settings).map_err(|e| e.to_string())?;
                let write = format!(
                    "set -e\nd={settings_dir}\nmkdir -p \"$d\"\n\
                     [ -f \"$d/settings.json\" ] && cp \"$d/settings.json\" \"$d/settings.json.burrow-bak\"\n\
                     cat > \"$d/settings.json.tmp\" <<'BURROW_EOF'\n{text}\nBURROW_EOF\n\
                     mv \"$d/settings.json.tmp\" \"$d/settings.json\"\n"
                );
                remote::side_command(&store, &profile, "sh -s", Some(write.as_bytes()))?;
            }
            Ok(InstallResult {
                settings: shown,
                added,
            })
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::io::Write as _;
    use std::process::Stdio;

    fn presets() -> GuardrailsFile {
        GuardrailsFile::default()
    }

    #[test]
    fn rules_file_quotes_and_stamps() {
        let mut file = presets();
        file.rules[0].label = "it's".into();
        let text = zsh_rules(&file);
        assert!(text.starts_with("# burrow-guardrails "));
        let out = Command::new("zsh")
            .args(["-f", "-c", &format!("{text}\nprint -r -- ${{#__burrow_guard_patterns}} \"$__burrow_guard_labels[1]\"")])
            .output()
            .unwrap();
        let enabled = file.rules.iter().filter(|r| r.enabled).count();
        assert_eq!(
            String::from_utf8_lossy(&out.stdout).trim(),
            format!("{enabled} it's")
        );
    }

    fn run_hook(hook: &str, input: &str) -> String {
        let mut child = Command::new("zsh")
            .args(["-f", "-c", hook])
            .stdin(Stdio::piped())
            .stdout(Stdio::piped())
            .spawn()
            .unwrap();
        child
            .stdin
            .take()
            .unwrap()
            .write_all(input.as_bytes())
            .unwrap();
        String::from_utf8(child.wait_with_output().unwrap().stdout).unwrap()
    }

    #[test]
    fn claude_hook_denies_block_rules_only() {
        let hook = claude_hook(&presets());
        let call = |cmd: &str| {
            let input =
                json!({"tool_name": "Bash", "tool_input": {"command": cmd, "description": "x"}});
            run_hook(&hook, &input.to_string())
        };
        let denied = call("cd /tmp && rm -rf ~");
        let v: Value = serde_json::from_str(denied.trim()).expect(&denied);
        assert_eq!(v["hookSpecificOutput"]["permissionDecision"], "deny");
        assert!(v["hookSpecificOutput"]["permissionDecisionReason"]
            .as_str()
            .unwrap()
            .contains("재귀 삭제"));
        assert_eq!(call("git push --force origin main").contains("deny"), true);
        // Escaped quotes inside the command don't hide it.
        assert!(call(r#"echo "x" && git push -f"#).contains("deny"));
        assert_eq!(call("ls -la"), "");
        // warn rules let agents through.
        assert_eq!(call("docker system prune -a"), "");
        // Other tools are none of its business.
        let edit = json!({"tool_name": "Edit", "tool_input": {"command": "rm -rf ~"}});
        assert_eq!(run_hook(&hook, &edit.to_string()), "");
    }

    #[test]
    fn targets_parse_exactly_what_the_ui_sends() {
        let remote: ClaudeTarget =
            serde_json::from_value(json!({"scope": "user", "profileId": "p1"})).unwrap();
        assert_eq!(
            remote,
            ClaudeTarget::User {
                profile_id: Some("p1".into())
            }
        );
        let project: ClaudeTarget =
            serde_json::from_value(json!({"scope": "project", "profileId": null, "dir": "/w/app"}))
                .unwrap();
        assert_eq!(
            project,
            ClaudeTarget::Project {
                profile_id: None,
                dir: "/w/app".into()
            }
        );
        // A misspelt field must fail loudly, never fall back to this Mac.
        assert!(serde_json::from_value::<ClaudeTarget>(
            json!({"scope": "user", "profile_id": "p1"})
        )
        .is_err());
    }

    #[test]
    fn settings_keep_their_key_order() {
        let mut settings: Value =
            serde_json::from_str(r#"{"zeta": 1, "alpha": 2, "hooks": {}}"#).unwrap();
        merge_settings(&mut settings, "x").unwrap();
        let text = serde_json::to_string(&settings).unwrap();
        assert!(
            text.find("zeta").unwrap() < text.find("alpha").unwrap(),
            "{text}"
        );
    }

    #[test]
    fn settings_merge_keeps_everything_else() {
        let mut settings = json!({
            "model": "opus",
            "hooks": {
                "PreToolUse": [{"matcher": "Edit", "hooks": [{"type": "command", "command": "lint"}]}],
                "Stop": [{"hooks": [{"type": "command", "command": "notify"}]}]
            }
        });
        assert!(merge_settings(&mut settings, "zsh '/h/hook'").unwrap());
        assert!(
            !merge_settings(&mut settings, "zsh '/h/hook'").unwrap(),
            "idempotent"
        );
        assert_eq!(settings["model"], "opus");
        assert_eq!(
            settings["hooks"]["Stop"][0]["hooks"][0]["command"],
            "notify"
        );
        let pre = settings["hooks"]["PreToolUse"].as_array().unwrap();
        assert_eq!(pre.len(), 2);
        assert_eq!(pre[1]["matcher"], "Bash");
        assert!(merge_settings(&mut json!([]), "x").is_err());
        assert!(parse_settings(Some("{ broken")).is_err());
        assert_eq!(parse_settings(None).unwrap(), json!({}));
    }

    #[test]
    fn pattern_test_uses_zsh_semantics() {
        let rules: Vec<(String, String)> = presets()
            .rules
            .iter()
            .map(|r| (r.id.clone(), r.pattern.clone()))
            .chain([("bad".to_string(), "(unclosed".to_string())])
            .collect();
        let r = guardrail_test("sudo rm -rf / ".into(), rules.clone()).unwrap();
        assert_eq!(r.matched, ["preset-rm-rf-root-home"]);
        assert_eq!(r.invalid, ["bad"]);
        assert!(guardrail_test("rm -rf ./build".into(), rules)
            .unwrap()
            .matched
            .is_empty());
    }
}
